openapi: 3.0.2
info:
  title: ITS Web API - OpenAPI 3.0
  description: |-
    ITS Web API based on the OpenAPI 3.0 specification
  version: 1.0.0
servers:
  - url: http://localhost:8000/its-web-api
tags:
  - name: market data
    description: Market Data related API

paths:
  /market-price/{marketCode}/{instrumentLocalCode}:
    get:
      tags:
        - market data
      summary: Get market price of instrument
      operationId: getInstrumentMarketPrice
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: marketCode
          schema:
            type: string
          required: true
          description: Market Code (e.g. HKG)
        - in: path
          name: instrumentLocalCode
          schema:
            type: string
          required: true
          description: Instrument Local Code (0005)
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketPrice'
        400:
          description: Input search criteria is invalid
          content:
            application/json:
              schema:
                $ref: "../../../../../resources/static/api-spec-component-1_0_0.yaml#/components/schemas/ErrorResponse"
        404:
          description: Instrument is not found
          content:
            application/json:
              schema:
                $ref: "../../../../../resources/static/api-spec-component-1_0_0.yaml#/components/schemas/ErrorResponse"
        500:
          description: Unexpected error occurrs
          content:
            application/json:
              schema:
                $ref: "../../../../../resources/static/api-spec-component-1_0_0.yaml#/components/schemas/ErrorResponse"

components:
  schemas:

    Currency:
      type: object
      required:
        - currencyCode
        - name
        - shortName
        - decimalPlace
      properties:
        currencyCode:
          type: string
          description: ISO Currency Code
          example: HKD
          minLength: 3
          maxLength: 3
        name:
          type: array
          items:
            type: object
            required:
              - locale
              - value
            properties:
              locale:
                type: string
                description: BCP-47 language tag
                example: en
                maxLength: 50
              value:
                type: string
                description: Currency name in language specified by locale
                example: Hong Kong Dollar
                maxLength: 50
        shortName:
          type: array
          items:
            type: object
            required:
              - locale
              - value
            properties:
              locale:
                type: string
                description: BCP-47 language tag
                example: zh-Hant
                maxLength: 10
              value:
                type: string
                description: Currency name in language specified by locale
                example: 港幣
                maxLength: 10
        decimalPlace:
          type: integer
          format: int32
          description: Number of decimal points supported

    MarketPrice:
      type: object
      required:
        - type
        - quotationTime
        - currency
        - price
      properties:
        type:
          type: string
          enum:
            - RealTime
            - Delayed
          x-enum-varnames:
            - REAL_TIME
            - DELAYED
        quotationTime:
          type: string
          format: 'date-time'
        currency:
          $ref: '#/components/schemas/Currency'
        price:
          type: number
          format: float
