spring:
  application:
    name: "its-webapi"
  redis:
    host: "localhost"
    port: 6379
application:
  cache:
    - name: "currency"
      # in minutes
      timeTolive: 10
  endPoint:
    ref-data: "http://localhost:9000/reference-data-service"
    mkt-data: "http://localhost:9100/market-data-service"
kafka:
  bootstrapAddress: "localhost:9092"
server:
  port : 8000
